version: 2.1
jobs:
  build:
    docker:
      - image: cypress/browsers:node14.17.0-chrome89-ff89
    working_directory: ~/app
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install
      - run:
          name: Run Cypress Tests
          command: npm run test